---
  ###########################################
  # Check gateways availability

  # Convert inventory into json
  - name: Convert inventory from csv into json
    shell: ../scripts/csvToJsonConverter.py {{ inventoryCSVfile }} {{ inventoryJsonfile }}
  #- meta: end_play

  - name: Print current time
    debug: msg={{ inventoryJsonfile }}    
  
  #- meta: end_play

  - name: Include vars
    include_vars:      
      file: "{{ inventoryJsonfile }}"

  - name: We will check the gateways availability here
    debug: msg="We will check the gateways availability here"
  
  - name: Get current time
    shell: date +%Y%m%d_%H%M%S
    register: curTime

  - name: Print current time
    debug: msg={{ curTime.stdout }}    

  - name: Create report file name
    shell: echo "{{ outputFolder }}/{{ outputFile }}{{ curTime.stdout }}.csv"
    register: reportFileFullName

  - name: Print reportFileFullName
    debug: msg={{ reportFileFullName.stdout }}  

  - name: Create output file, write header
    shell: echo "#cma;gw_name;gw_ip;icmp;ssh;https" > {{ reportFileFullName.stdout }}

  #- meta: end_play  

  # Iterate over gateways from json file
  - name: main loop
    include_tasks: innerTasks.yml
    with_items:
      - "{{ gateways }}"
  # An attempt to parallelization. It doesn't work.  
  #  async: 40
  #  poll: 5    

  

